/* CHECK FOR NULL VALUES IN CITY*/
SELECT
   *
FROM customers
WHERE City IS NULL;

/* CHECK NULL VALUES IN PAYMENT METHOD*/
SELECT
   *
FROM orders
WHERE Payment_Method IS NULL;

/* CHECK FOR DUPLICATE VALUES */
SELECT
    Order_ID,
    COUNT(*)
FROM orders
GROUP BY Order_ID
HAVING COUNT(*) > 1;


/* CREATING A MERGE TABLE FOR ANALYSIS */
SELECT
     o.Order_ID,
     o.Customer_ID,
     ISNULL(City,'UNKNOWN') AS City,
     o.Order_Date,
     o.Payment_Method,
     o.Delivery_Status,
     o.Total_Amount
INTO sales
FROM orders o
LEFT JOIN customers c
ON o.Customer_ID = c.Customer_ID;


/* PREVIEW TABLE*/
SELECT  COUNT(*)
FROM sales
WHERE City = 'UNKNOWN';



/* ANALYSIS QUESTONS*/
/* TOTAL REVENUE GENERATED BY EACH CITY*/
SELECT
     City,
     SUM(Total_Amount) AS REVENUE
FROM sales
GROUP BY City
ORDER BY REVENUE DESC;


/* PAYMENT METHOD USAGE */
SELECT
    Payment_Method,
    COUNT(*) AS orders_count
FROM sales
GROUP BY Payment_Method
ORDER BY COUNT(*) DESC;


/* MONTHLY REVENUE*/
SELECT
    MONTH(Order_Date) AS Month,
    SUM(Total_Amount) AS Total_Revenue
FROM sales
GROUP BY MONTH(Order_Date)
ORDER BY SUM(Total_Amount) DESC;


/* DELIVERY STATUS*/
SELECT
     Delivery_Status,
     COUNT(*)
FROM sales
GROUP BY Delivery_Status;
